### ISSUE TITLE
Search-box shouldn't be hidden when small screen size

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-bootstrap#12]
The bootstrap responsive CSS hides the search-box when screen/browser is small. We need to figure out another way of displaying the search box when small screen real estate.

**Small screen:**
![screen shot 2015-01-29 at 17 57 31](https://cloud.githubusercontent.com/assets/236656/5961974/9fe765cc-a7e0-11e4-8651-345d18ab2688.png)

**A bit bigger:**
![screen shot 2015-01-29 at 18 00 17](https://cloud.githubusercontent.com/assets/236656/5961988/b9efb76c-a7e0-11e4-8fe5-f269dc89a64c.png)

**Comment by fergiemcdowall** [comment]
This is the bootstrap "way". If you click the little box with the lines in it, the search box should appear. Does that work for you?

**Comment by fergiemcdowall** [comment]
(little box with the lines in it is on the right hand side of the grey bar at the top)

**Comment by eklem** [comment]
Yes, but thinking that the search box is too important to be hidden. The facets/filters can be hidden, but not the search box. I'll make a mockup, discuss, and then try to fix and do a pull request.

**Comment by eklem** [comment]
Also, because of the other menu choices and on-screen keyboard, it's hard to tell if you have gotten a search result or not. https://cloud.githubusercontent.com/assets/236656/6425858/01e4eafe-bf3f-11e4-8e5f-f1af249284a3.png

**Comment by fergiemcdowall** [comment]
I see what you mean.
