### ISSUE TITLE
Search input box too wide for cellphone

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-bootstrap#18]
![16463066367_2d8d3b7d4e_o](https://cloud.githubusercontent.com/assets/236656/6425858/01e4eafe-bf3f-11e4-8e5f-f1af249284a3.png)

Just some css that needs to be adjusted...

**Comment by fergiemcdowall** [comment]
I thought the search box was hidden by default on the cellphone and only appeared when you clicked the control to the top right.

Maybe it will be fixed by updating the bootstrap libs?

**Comment by eklem** [comment]
It's hidden by default, but when you press the burger icon, and the search box and "add", "delete" and "documentation"-choices become visible, the search box is too wide for the screen.

**Comment by fergiemcdowall** [comment]
Ahh I see. In that case its a Bootstrap bug which may or may not be fixed in the latest version,

(+1 for "burger icon" ;)

**Comment by eklem** [comment]
Hehe, I didn't coin the burger icon, but it's a good phrase. This is not a biggie, so I'll use it to learn some git pull request-stuff and get more familiar with the bootstrap-code.

**Comment by mewwts** [comment]
:+1: @eklem!
