### ISSUE TITLE
Error message: Cannot GET /

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-bootstrap#19]
Install norch, index some tweets and run the API successfully:
![skjermbilde 2015-03-07 kl 13 49 55](https://cloud.githubusercontent.com/assets/236656/6541447/09507d34-c4d1-11e4-80b5-ebe1cbbe766a.png)

But when I try the actual web frontend:
![skjermbilde 2015-03-07 kl 13 51 53](https://cloud.githubusercontent.com/assets/236656/6541449/24904ef8-c4d1-11e4-9755-51d55559e5df.png)

Same error message if I do: http://10.0.1.14:3030/
Guessing this is a `norch-bootstrap` issue since the API is working.

**Comment by eklem** [comment]
Installed via npm on a Raspberry Pi 2, but think I got the same error on OSX the other day.

**Comment by fergiemcdowall** [comment]
You need to take away the ´#´

So http://1.0.1.14:3030/search?q=* should work

**Comment by eklem** [comment]
Ok, but that only gives me the API, where's the norch-bootstrap?
If i do http://10.0.1.14:3030/ i get the error message:
`Cannot GET /`

**Comment by fergiemcdowall** [comment]
Oh I see, yes norch-bootstrap should be on http://10.0.1.14:3030/

I wonder if this is because you are on an "unusual" ip address. Have you tried setting the hostname to "10.0.1.14" as per the startup options here: https://github.com/fergiemcdowall/norch#startup-options

**Comment by fergiemcdowall** [comment]
Or maybe thats got nothing to do with it

**Comment by eklem** [comment]
Same issue. This has also worked earlier on port 10.0.1.78

```
pi@fatboy ~ $ node node_modules/.bin/norch -p 3030 -n 10.0.1.14

      ___           ___           ___           ___           ___
     /\__\         /\  \         /\  \         /\  \         /\__\
    /::|  |       /::\  \       /::\  \       /::\  \       /:/  /
   /:|:|  |      /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/__/
  /:/|:|  |__   /:/  \:\  \   /::\~\:\  \   /:/  \:\  \   /::\  \ ___
 /:/ |:| /\__\ /:/__/ \:\__\ /:/\:\ \:\__\ /:/__/ \:\__\ /:/\:\  /\__\
 \/__|:|/:/  / \:\  \ /:/  / \/_|::\/:/  / \:\  \  \/__/ \/__\:\/:/  /
     |:/:/  /   \:\  /:/  /     |:|::/  /   \:\  \            \::/  /
     |::/  /     \:\/:/  /      |:|\/__/     \:\  \           /:/  /
     /:/  /       \::/  /       |:|  |        \:\__\         /:/  /
     \/__/         \/__/         \|__|         \/__/         \/__/

MIT license, 2013-2014
http://fergiemcdowall.github.io/Norch

Norch server listening on hostname 10.0.1.14 on port 3030

GET / 404 13 - 93.105 ms
```

**Comment by fergiemcdowall** [comment]
Hmmmmm- will look into it

**Comment by eklem** [comment]
Some installation hickup. ´npm remove norch´ and ´npm install norch´ did the trick.
