### ISSUE TITLE
How to best have several templates to choose from?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-bootstrap#24]
The default template should list out all field names and field content. It can be made a little better, but should show 'out of the box' what's available to play with. A more polished one could fit a certain data set, like the [reuters-21578-json](https://github.com/fergiemcdowall/reuters-21578-json) or the [world-bank-dataset](https://github.com/fergiemcdowall/world-bank-dataset), and could be named `norch-bootstrap-reuters-21578` and `norch-bootstrap-world-bank-dataset`.

The question I got is how to do it best. should these templates be a sub-set/module for `norch-bootstrap` to require. Something like:
```javascript
var template = require('norch-bootstrap-reuters-21578')
```
Or simply be a fork of norch-bootstrap? Then we can explain in the documentation that you just change this variable to change template:
```javascript
  this.app.use(this.express.static(this.path.join(__dirname,
                                   '../node_modules/norch-bootstrap')));
```

I got the idea to have it as a subset first, but a fork seems better since there's not that much extra code (bootstrap-stuff) that will change over time. Maybe we can do it the other way around: Require the bootstrap-stuff into the `norch-bootstrap`, so it's easy to upgrade the actual bootstrap?

**Comment by fergiemcdowall** [comment]
It would be really nice to provide a pluggable front end with a dataset.

Its definitely best to keep an agnostic front end as default

**Comment by eklem** [comment]
Then my suggestion is:
In norch-bootstrap, we'll stop including the bootstrap files, we just link them from the html, something like this:

```html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
```

Then, all that is left in norch-bootstrap is some html-files (Angular) and a custom css. When people fork it, they only fork the code they will re-code. This will mean they don't create a lot of non-updated bootstrap-code. Maybe we should create a new module called norch-template, or rename norch-bootstrap?

**Comment by fergiemcdowall** [comment]
Yes, thats a good idea.

**Comment by eklem** [comment]
Cool (= Thank you, @mewwts for the suggestion to just link in bootstrap stuff.

**Comment by mewwts** [comment]
:+1:
