### ISSUE TITLE
autosuggest doesn't handle "ø" that well

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-bootstrap#7]
Seems "ø" breaks up the word indexing. "overfl" and "dig" is what's indexed.

![screen shot 2014-12-04 at 13 28 19](https://cloud.githubusercontent.com/assets/236656/5298270/8c23d2bc-7bb9-11e4-9be9-6309abde3d74.png)
Autosuggest on "overfl" even if there's no "overfl"-words in the index only one "overflødig".

![screen shot 2014-12-04 at 13 31 54](https://cloud.githubusercontent.com/assets/236656/5298293/ee8193fe-7bb9-11e4-8723-c2df31fa7c46.png)

![screen shot 2014-12-04 at 13 31 18](https://cloud.githubusercontent.com/assets/236656/5298287/d896f660-7bb9-11e4-88eb-e8df186efe44.png)

**Comment by eklem** [comment]
Also, doesn't get matches on words with æ,ø or å. Here's a JSON-example that will generate no hits on `Ålfjel`, but one hit on `Vaset`:
```
{
    "date":"2014-11-12T09:50:00+01:00",
    "dateuploaded":"2014-10-19T16:35:00+02:00",
    "title":"Ålfjell, Vaset, Valdres",
    "text":null,
    "url":"http://flic.kr/p/pKhDKo",
    "image":"",
    "urlimage":"https://farm6.staticflickr.com/5616/15586063768_cb4e444961_o.jpg",
    "tags":null,
    "user":[
      "eklem"
    ],
    "type":[
      "Flickr"
    ],
    "id":"4G5ras"
  }
```

**Comment by fergiemcdowall** [comment]
Darn. Need to fix this ASAP.

**Comment by eklem** [comment]
I'll check this tomorrow, since you got a `search-index`-fix for similar bug:
https://github.com/fergiemcdowall/search-index/commit/b291e1702a28d93ca51453d82a152a41a45e732a

**Comment by fergiemcdowall** [comment]
Fixed in `search-index`, but not pushed upstream to `norch` just yet...

**Comment by eklem** [comment]
Let me know!

**Comment by eklem** [comment]
This works because of fix on `search-index` bug: https://github.com/fergiemcdowall/search-index/issues/75
